name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - .editorconfig
      - .gitignore
      - .dockerignore
  pull_request:
    branches: [ "develop" ]
    paths-ignore:
      - .editorconfig
      - .gitignore
      - .dockerignore
  # Allow to run the action manually
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checking out the repository
        uses: actions/checkout@v3
      -
        name: Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      -
        name: Logging in docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push to registry
        uses: docker/build-push-action@v5.1.0
        with:
          file: ./src/Presentation/Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mg.cinema:${{ github.run_number }}, ${{ secrets.DOCKERHUB_USERNAME }}/mg.cinema:latest
